
name: Java Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install missing dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff2dec.so.1.0.2
          libvpx.so.7 \
          libevent-2.1.so.7 \
          libopus.so.0 \
          libharfbuzz-icu.so.0 \
          libgstallocators-1.0.so.0 \
          libgstapp-1.0.so.0 \
          libgstpbutils-1.0.so.0 \
          libgstaudio-1.0.so.0 \
          libgsttag-1.0.so.0 \
          libgstvideo-1.0.so.0 \
          libgstgl-1.0.so.0 \
          libgstcodecparsers-1.0.so.0 \
          libgstfft-1.0.so.0 \
          libhyphen.so.0 \
          libmanette-0.2.so.0 \
          libflite.so.1 \
          libflite_usenglish.so.1 \
          libflite_cmu_grapheme_lang.so.1 \
          libflite_cmu_grapheme_lex.so.1 \
          libflite_cmu_indic_lang.so.1 \
          libflite_cmu_indic_lex.so.1 \
          libflite_cmulex.so.1 \
          libflite_cmu_time_awb.so.1 \
          libflite_cmu_us_awb.so.1 \
          libflite_cmu_us_kal16.so.1 \
          libflite_cmu_us_kal.so.1 \
          libflite_cmu_us_rms.so.1 \
          libflite_cmu_us_slt.so.1 \
          libGLESv2.so.2 \
          libx264.so \
          
    - uses: actions/checkout@v4
    - name: Set up Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Playwright dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests 
      run: mvn test
