
name: Java Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Playwright dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Run Java tests
    - name: Run tests
      run: mvn test
